// Code generated by entc, DO NOT EDIT.

package medicalfile

const (
	// Label holds the string label denoting the medicalfile type in the database.
	Label = "medicalfile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// EdgeDentist holds the string denoting the dentist edge name in mutations.
	EdgeDentist = "dentist"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"

	// Table holds the table name of the medicalfile in the database.
	Table = "medicalfiles"
	// DentistTable is the table the holds the dentist relation/edge.
	DentistTable = "medicalfiles"
	// DentistInverseTable is the table name for the Dentist entity.
	// It exists in this package in order to avoid circular dependency with the "dentist" package.
	DentistInverseTable = "dentists"
	// DentistColumn is the table column denoting the dentist relation/edge.
	DentistColumn = "dentist_id"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "medicalfiles"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "medicalfiles"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_id"
)

// Columns holds all SQL columns for medicalfile fields.
var Columns = []string{
	FieldID,
	FieldDetail,
	FieldAddedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Medicalfile type.
var ForeignKeys = []string{
	"dentist_id",
	"employee_id",
	"patient_id",
}

var (
	// DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	DetailValidator func(string) error
)
