// Code generated by entc, DO NOT EDIT.

package dentist

const (
	// Label holds the string label denoting the dentist type in the database.
	Label = "dentist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeMedicalfiles holds the string denoting the medicalfiles edge name in mutations.
	EdgeMedicalfiles = "medicalfiles"

	// Table holds the table name of the dentist in the database.
	Table = "dentists"
	// MedicalfilesTable is the table the holds the medicalfiles relation/edge.
	MedicalfilesTable = "medicalfiles"
	// MedicalfilesInverseTable is the table name for the Medicalfile entity.
	// It exists in this package in order to avoid circular dependency with the "medicalfile" package.
	MedicalfilesInverseTable = "medicalfiles"
	// MedicalfilesColumn is the table column denoting the medicalfiles relation/edge.
	MedicalfilesColumn = "dentist_id"
)

// Columns holds all SQL columns for dentist fields.
var Columns = []string{
	FieldID,
	FieldName,
}
