// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/kaews/app/ent/migrate"

	"github.com/kaews/app/ent/dentist"
	"github.com/kaews/app/ent/employee"
	"github.com/kaews/app/ent/medicalfile"
	"github.com/kaews/app/ent/patient"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Dentist is the client for interacting with the Dentist builders.
	Dentist *DentistClient
	// Employee is the client for interacting with the Employee builders.
	Employee *EmployeeClient
	// Medicalfile is the client for interacting with the Medicalfile builders.
	Medicalfile *MedicalfileClient
	// Patient is the client for interacting with the Patient builders.
	Patient *PatientClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Dentist = NewDentistClient(c.config)
	c.Employee = NewEmployeeClient(c.config)
	c.Medicalfile = NewMedicalfileClient(c.config)
	c.Patient = NewPatientClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Dentist:     NewDentistClient(cfg),
		Employee:    NewEmployeeClient(cfg),
		Medicalfile: NewMedicalfileClient(cfg),
		Patient:     NewPatientClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:      cfg,
		Dentist:     NewDentistClient(cfg),
		Employee:    NewEmployeeClient(cfg),
		Medicalfile: NewMedicalfileClient(cfg),
		Patient:     NewPatientClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Dentist.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Dentist.Use(hooks...)
	c.Employee.Use(hooks...)
	c.Medicalfile.Use(hooks...)
	c.Patient.Use(hooks...)
}

// DentistClient is a client for the Dentist schema.
type DentistClient struct {
	config
}

// NewDentistClient returns a client for the Dentist from the given config.
func NewDentistClient(c config) *DentistClient {
	return &DentistClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dentist.Hooks(f(g(h())))`.
func (c *DentistClient) Use(hooks ...Hook) {
	c.hooks.Dentist = append(c.hooks.Dentist, hooks...)
}

// Create returns a create builder for Dentist.
func (c *DentistClient) Create() *DentistCreate {
	mutation := newDentistMutation(c.config, OpCreate)
	return &DentistCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Dentist.
func (c *DentistClient) Update() *DentistUpdate {
	mutation := newDentistMutation(c.config, OpUpdate)
	return &DentistUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DentistClient) UpdateOne(d *Dentist) *DentistUpdateOne {
	mutation := newDentistMutation(c.config, OpUpdateOne, withDentist(d))
	return &DentistUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DentistClient) UpdateOneID(id int) *DentistUpdateOne {
	mutation := newDentistMutation(c.config, OpUpdateOne, withDentistID(id))
	return &DentistUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Dentist.
func (c *DentistClient) Delete() *DentistDelete {
	mutation := newDentistMutation(c.config, OpDelete)
	return &DentistDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DentistClient) DeleteOne(d *Dentist) *DentistDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DentistClient) DeleteOneID(id int) *DentistDeleteOne {
	builder := c.Delete().Where(dentist.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DentistDeleteOne{builder}
}

// Create returns a query builder for Dentist.
func (c *DentistClient) Query() *DentistQuery {
	return &DentistQuery{config: c.config}
}

// Get returns a Dentist entity by its id.
func (c *DentistClient) Get(ctx context.Context, id int) (*Dentist, error) {
	return c.Query().Where(dentist.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DentistClient) GetX(ctx context.Context, id int) *Dentist {
	d, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return d
}

// QueryMedicalfiles queries the medicalfiles edge of a Dentist.
func (c *DentistClient) QueryMedicalfiles(d *Dentist) *MedicalfileQuery {
	query := &MedicalfileQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dentist.Table, dentist.FieldID, id),
			sqlgraph.To(medicalfile.Table, medicalfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dentist.MedicalfilesTable, dentist.MedicalfilesColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DentistClient) Hooks() []Hook {
	return c.hooks.Dentist
}

// EmployeeClient is a client for the Employee schema.
type EmployeeClient struct {
	config
}

// NewEmployeeClient returns a client for the Employee from the given config.
func NewEmployeeClient(c config) *EmployeeClient {
	return &EmployeeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employee.Hooks(f(g(h())))`.
func (c *EmployeeClient) Use(hooks ...Hook) {
	c.hooks.Employee = append(c.hooks.Employee, hooks...)
}

// Create returns a create builder for Employee.
func (c *EmployeeClient) Create() *EmployeeCreate {
	mutation := newEmployeeMutation(c.config, OpCreate)
	return &EmployeeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Employee.
func (c *EmployeeClient) Update() *EmployeeUpdate {
	mutation := newEmployeeMutation(c.config, OpUpdate)
	return &EmployeeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmployeeClient) UpdateOne(e *Employee) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployee(e))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmployeeClient) UpdateOneID(id int) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployeeID(id))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Employee.
func (c *EmployeeClient) Delete() *EmployeeDelete {
	mutation := newEmployeeMutation(c.config, OpDelete)
	return &EmployeeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *EmployeeClient) DeleteOne(e *Employee) *EmployeeDeleteOne {
	return c.DeleteOneID(e.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *EmployeeClient) DeleteOneID(id int) *EmployeeDeleteOne {
	builder := c.Delete().Where(employee.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmployeeDeleteOne{builder}
}

// Create returns a query builder for Employee.
func (c *EmployeeClient) Query() *EmployeeQuery {
	return &EmployeeQuery{config: c.config}
}

// Get returns a Employee entity by its id.
func (c *EmployeeClient) Get(ctx context.Context, id int) (*Employee, error) {
	return c.Query().Where(employee.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmployeeClient) GetX(ctx context.Context, id int) *Employee {
	e, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return e
}

// QueryMedicalfiles queries the medicalfiles edge of a Employee.
func (c *EmployeeClient) QueryMedicalfiles(e *Employee) *MedicalfileQuery {
	query := &MedicalfileQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := e.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(employee.Table, employee.FieldID, id),
			sqlgraph.To(medicalfile.Table, medicalfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, employee.MedicalfilesTable, employee.MedicalfilesColumn),
		)
		fromV = sqlgraph.Neighbors(e.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmployeeClient) Hooks() []Hook {
	return c.hooks.Employee
}

// MedicalfileClient is a client for the Medicalfile schema.
type MedicalfileClient struct {
	config
}

// NewMedicalfileClient returns a client for the Medicalfile from the given config.
func NewMedicalfileClient(c config) *MedicalfileClient {
	return &MedicalfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `medicalfile.Hooks(f(g(h())))`.
func (c *MedicalfileClient) Use(hooks ...Hook) {
	c.hooks.Medicalfile = append(c.hooks.Medicalfile, hooks...)
}

// Create returns a create builder for Medicalfile.
func (c *MedicalfileClient) Create() *MedicalfileCreate {
	mutation := newMedicalfileMutation(c.config, OpCreate)
	return &MedicalfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Medicalfile.
func (c *MedicalfileClient) Update() *MedicalfileUpdate {
	mutation := newMedicalfileMutation(c.config, OpUpdate)
	return &MedicalfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MedicalfileClient) UpdateOne(m *Medicalfile) *MedicalfileUpdateOne {
	mutation := newMedicalfileMutation(c.config, OpUpdateOne, withMedicalfile(m))
	return &MedicalfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MedicalfileClient) UpdateOneID(id int) *MedicalfileUpdateOne {
	mutation := newMedicalfileMutation(c.config, OpUpdateOne, withMedicalfileID(id))
	return &MedicalfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Medicalfile.
func (c *MedicalfileClient) Delete() *MedicalfileDelete {
	mutation := newMedicalfileMutation(c.config, OpDelete)
	return &MedicalfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MedicalfileClient) DeleteOne(m *Medicalfile) *MedicalfileDeleteOne {
	return c.DeleteOneID(m.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MedicalfileClient) DeleteOneID(id int) *MedicalfileDeleteOne {
	builder := c.Delete().Where(medicalfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MedicalfileDeleteOne{builder}
}

// Create returns a query builder for Medicalfile.
func (c *MedicalfileClient) Query() *MedicalfileQuery {
	return &MedicalfileQuery{config: c.config}
}

// Get returns a Medicalfile entity by its id.
func (c *MedicalfileClient) Get(ctx context.Context, id int) (*Medicalfile, error) {
	return c.Query().Where(medicalfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MedicalfileClient) GetX(ctx context.Context, id int) *Medicalfile {
	m, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return m
}

// QueryDentist queries the dentist edge of a Medicalfile.
func (c *MedicalfileClient) QueryDentist(m *Medicalfile) *DentistQuery {
	query := &DentistQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(medicalfile.Table, medicalfile.FieldID, id),
			sqlgraph.To(dentist.Table, dentist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, medicalfile.DentistTable, medicalfile.DentistColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPatient queries the patient edge of a Medicalfile.
func (c *MedicalfileClient) QueryPatient(m *Medicalfile) *PatientQuery {
	query := &PatientQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(medicalfile.Table, medicalfile.FieldID, id),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, medicalfile.PatientTable, medicalfile.PatientColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmployee queries the employee edge of a Medicalfile.
func (c *MedicalfileClient) QueryEmployee(m *Medicalfile) *EmployeeQuery {
	query := &EmployeeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(medicalfile.Table, medicalfile.FieldID, id),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, medicalfile.EmployeeTable, medicalfile.EmployeeColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MedicalfileClient) Hooks() []Hook {
	return c.hooks.Medicalfile
}

// PatientClient is a client for the Patient schema.
type PatientClient struct {
	config
}

// NewPatientClient returns a client for the Patient from the given config.
func NewPatientClient(c config) *PatientClient {
	return &PatientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `patient.Hooks(f(g(h())))`.
func (c *PatientClient) Use(hooks ...Hook) {
	c.hooks.Patient = append(c.hooks.Patient, hooks...)
}

// Create returns a create builder for Patient.
func (c *PatientClient) Create() *PatientCreate {
	mutation := newPatientMutation(c.config, OpCreate)
	return &PatientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Patient.
func (c *PatientClient) Update() *PatientUpdate {
	mutation := newPatientMutation(c.config, OpUpdate)
	return &PatientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PatientClient) UpdateOne(pa *Patient) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatient(pa))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PatientClient) UpdateOneID(id int) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatientID(id))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Patient.
func (c *PatientClient) Delete() *PatientDelete {
	mutation := newPatientMutation(c.config, OpDelete)
	return &PatientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *PatientClient) DeleteOne(pa *Patient) *PatientDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *PatientClient) DeleteOneID(id int) *PatientDeleteOne {
	builder := c.Delete().Where(patient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PatientDeleteOne{builder}
}

// Create returns a query builder for Patient.
func (c *PatientClient) Query() *PatientQuery {
	return &PatientQuery{config: c.config}
}

// Get returns a Patient entity by its id.
func (c *PatientClient) Get(ctx context.Context, id int) (*Patient, error) {
	return c.Query().Where(patient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PatientClient) GetX(ctx context.Context, id int) *Patient {
	pa, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return pa
}

// QueryMedicalfiles queries the medicalfiles edge of a Patient.
func (c *PatientClient) QueryMedicalfiles(pa *Patient) *MedicalfileQuery {
	query := &MedicalfileQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(patient.Table, patient.FieldID, id),
			sqlgraph.To(medicalfile.Table, medicalfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, patient.MedicalfilesTable, patient.MedicalfilesColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PatientClient) Hooks() []Hook {
	return c.hooks.Patient
}
