// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/kaews/app/ent/dentist"
	"github.com/kaews/app/ent/medicalfile"
)

// DentistCreate is the builder for creating a Dentist entity.
type DentistCreate struct {
	config
	mutation *DentistMutation
	hooks    []Hook
}

// SetName sets the name field.
func (dc *DentistCreate) SetName(s string) *DentistCreate {
	dc.mutation.SetName(s)
	return dc
}

// AddMedicalfileIDs adds the medicalfiles edge to Medicalfile by ids.
func (dc *DentistCreate) AddMedicalfileIDs(ids ...int) *DentistCreate {
	dc.mutation.AddMedicalfileIDs(ids...)
	return dc
}

// AddMedicalfiles adds the medicalfiles edges to Medicalfile.
func (dc *DentistCreate) AddMedicalfiles(m ...*Medicalfile) *DentistCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dc.AddMedicalfileIDs(ids...)
}

// Mutation returns the DentistMutation object of the builder.
func (dc *DentistCreate) Mutation() *DentistMutation {
	return dc.mutation
}

// Save creates the Dentist in the database.
func (dc *DentistCreate) Save(ctx context.Context) (*Dentist, error) {
	if _, ok := dc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	var (
		err  error
		node *Dentist
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DentistMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DentistCreate) SaveX(ctx context.Context) *Dentist {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DentistCreate) sqlSave(ctx context.Context) (*Dentist, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DentistCreate) createSpec() (*Dentist, *sqlgraph.CreateSpec) {
	var (
		d     = &Dentist{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: dentist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dentist.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dentist.FieldName,
		})
		d.Name = value
	}
	if nodes := dc.mutation.MedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.MedicalfilesTable,
			Columns: []string{dentist.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
