// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/kaews/app/ent/dentist"
	"github.com/kaews/app/ent/medicalfile"
	"github.com/kaews/app/ent/predicate"
)

// DentistUpdate is the builder for updating Dentist entities.
type DentistUpdate struct {
	config
	hooks      []Hook
	mutation   *DentistMutation
	predicates []predicate.Dentist
}

// Where adds a new predicate for the builder.
func (du *DentistUpdate) Where(ps ...predicate.Dentist) *DentistUpdate {
	du.predicates = append(du.predicates, ps...)
	return du
}

// SetName sets the name field.
func (du *DentistUpdate) SetName(s string) *DentistUpdate {
	du.mutation.SetName(s)
	return du
}

// AddMedicalfileIDs adds the medicalfiles edge to Medicalfile by ids.
func (du *DentistUpdate) AddMedicalfileIDs(ids ...int) *DentistUpdate {
	du.mutation.AddMedicalfileIDs(ids...)
	return du
}

// AddMedicalfiles adds the medicalfiles edges to Medicalfile.
func (du *DentistUpdate) AddMedicalfiles(m ...*Medicalfile) *DentistUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return du.AddMedicalfileIDs(ids...)
}

// Mutation returns the DentistMutation object of the builder.
func (du *DentistUpdate) Mutation() *DentistMutation {
	return du.mutation
}

// RemoveMedicalfileIDs removes the medicalfiles edge to Medicalfile by ids.
func (du *DentistUpdate) RemoveMedicalfileIDs(ids ...int) *DentistUpdate {
	du.mutation.RemoveMedicalfileIDs(ids...)
	return du
}

// RemoveMedicalfiles removes medicalfiles edges to Medicalfile.
func (du *DentistUpdate) RemoveMedicalfiles(m ...*Medicalfile) *DentistUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return du.RemoveMedicalfileIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (du *DentistUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DentistMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DentistUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DentistUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DentistUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DentistUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dentist.Table,
			Columns: dentist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dentist.FieldID,
			},
		},
	}
	if ps := du.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dentist.FieldName,
		})
	}
	if nodes := du.mutation.RemovedMedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.MedicalfilesTable,
			Columns: []string{dentist.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.MedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.MedicalfilesTable,
			Columns: []string{dentist.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dentist.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DentistUpdateOne is the builder for updating a single Dentist entity.
type DentistUpdateOne struct {
	config
	hooks    []Hook
	mutation *DentistMutation
}

// SetName sets the name field.
func (duo *DentistUpdateOne) SetName(s string) *DentistUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// AddMedicalfileIDs adds the medicalfiles edge to Medicalfile by ids.
func (duo *DentistUpdateOne) AddMedicalfileIDs(ids ...int) *DentistUpdateOne {
	duo.mutation.AddMedicalfileIDs(ids...)
	return duo
}

// AddMedicalfiles adds the medicalfiles edges to Medicalfile.
func (duo *DentistUpdateOne) AddMedicalfiles(m ...*Medicalfile) *DentistUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return duo.AddMedicalfileIDs(ids...)
}

// Mutation returns the DentistMutation object of the builder.
func (duo *DentistUpdateOne) Mutation() *DentistMutation {
	return duo.mutation
}

// RemoveMedicalfileIDs removes the medicalfiles edge to Medicalfile by ids.
func (duo *DentistUpdateOne) RemoveMedicalfileIDs(ids ...int) *DentistUpdateOne {
	duo.mutation.RemoveMedicalfileIDs(ids...)
	return duo
}

// RemoveMedicalfiles removes medicalfiles edges to Medicalfile.
func (duo *DentistUpdateOne) RemoveMedicalfiles(m ...*Medicalfile) *DentistUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return duo.RemoveMedicalfileIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (duo *DentistUpdateOne) Save(ctx context.Context) (*Dentist, error) {

	var (
		err  error
		node *Dentist
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DentistMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DentistUpdateOne) SaveX(ctx context.Context) *Dentist {
	d, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return d
}

// Exec executes the query on the entity.
func (duo *DentistUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DentistUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DentistUpdateOne) sqlSave(ctx context.Context) (d *Dentist, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dentist.Table,
			Columns: dentist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dentist.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Dentist.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := duo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dentist.FieldName,
		})
	}
	if nodes := duo.mutation.RemovedMedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.MedicalfilesTable,
			Columns: []string{dentist.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.MedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.MedicalfilesTable,
			Columns: []string{dentist.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	d = &Dentist{config: duo.config}
	_spec.Assign = d.assignValues
	_spec.ScanValues = d.scanValues()
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dentist.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return d, nil
}
