// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/kaews/app/ent/dentist"
)

// Dentist is the model entity for the Dentist schema.
type Dentist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DentistQuery when eager-loading is set.
	Edges DentistEdges `json:"edges"`
}

// DentistEdges holds the relations/edges for other nodes in the graph.
type DentistEdges struct {
	// Medicalfiles holds the value of the medicalfiles edge.
	Medicalfiles []*Medicalfile
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MedicalfilesOrErr returns the Medicalfiles value or an error if the edge
// was not loaded in eager-loading.
func (e DentistEdges) MedicalfilesOrErr() ([]*Medicalfile, error) {
	if e.loadedTypes[0] {
		return e.Medicalfiles, nil
	}
	return nil, &NotLoadedError{edge: "medicalfiles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dentist) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dentist fields.
func (d *Dentist) assignValues(values ...interface{}) error {
	if m, n := len(values), len(dentist.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		d.Name = value.String
	}
	return nil
}

// QueryMedicalfiles queries the medicalfiles edge of the Dentist.
func (d *Dentist) QueryMedicalfiles() *MedicalfileQuery {
	return (&DentistClient{config: d.config}).QueryMedicalfiles(d)
}

// Update returns a builder for updating this Dentist.
// Note that, you need to call Dentist.Unwrap() before calling this method, if this Dentist
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dentist) Update() *DentistUpdateOne {
	return (&DentistClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Dentist) Unwrap() *Dentist {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dentist is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dentist) String() string {
	var builder strings.Builder
	builder.WriteString("Dentist(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", name=")
	builder.WriteString(d.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Dentists is a parsable slice of Dentist.
type Dentists []*Dentist

func (d Dentists) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
