/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDentistEdges,
    EntDentistEdgesFromJSON,
    EntDentistEdgesFromJSONTyped,
    EntDentistEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDentist
 */
export interface EntDentist {
    /**
     * 
     * @type {EntDentistEdges}
     * @memberof EntDentist
     */
    edges?: EntDentistEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDentist
     */
    id?: number;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntDentist
     */
    name?: string;
}

export function EntDentistFromJSON(json: any): EntDentist {
    return EntDentistFromJSONTyped(json, false);
}

export function EntDentistFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDentist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntDentistEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntDentistToJSON(value?: EntDentist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntDentistEdgesToJSON(value.edges),
        'id': value.id,
        'name': value.name,
    };
}


