/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDentist,
    EntDentistFromJSON,
    EntDentistFromJSONTyped,
    EntDentistToJSON,
    EntEmployee,
    EntEmployeeFromJSON,
    EntEmployeeFromJSONTyped,
    EntEmployeeToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicalfileEdges
 */
export interface EntMedicalfileEdges {
    /**
     * 
     * @type {EntDentist}
     * @memberof EntMedicalfileEdges
     */
    dentist?: EntDentist;
    /**
     * 
     * @type {EntEmployee}
     * @memberof EntMedicalfileEdges
     */
    employee?: EntEmployee;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntMedicalfileEdges
     */
    patient?: EntPatient;
}

export function EntMedicalfileEdgesFromJSON(json: any): EntMedicalfileEdges {
    return EntMedicalfileEdgesFromJSONTyped(json, false);
}

export function EntMedicalfileEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicalfileEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dentist': !exists(json, 'Dentist') ? undefined : EntDentistFromJSON(json['Dentist']),
        'employee': !exists(json, 'Employee') ? undefined : EntEmployeeFromJSON(json['Employee']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
    };
}

export function EntMedicalfileEdgesToJSON(value?: EntMedicalfileEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dentist': EntDentistToJSON(value.dentist),
        'employee': EntEmployeeToJSON(value.employee),
        'patient': EntPatientToJSON(value.patient),
    };
}


